pull_request_template.md

** link to Trello Ticket **
** Summary **
** Test plan **
will look something like this

small fix on the github pr template

---

App.js
components/CommonCompStreak.js
package-lock.json
package.json
screens/Dashboard.js

https://trello.com/c/4ot20OlG/8-streak-component
This PR sets up the dashboard page with two streak components that have not yet being colored. This is also to make sure we don't block dashboard components.
n/a

Added barebone streak component

---

components/CommonCompGroupUser.js
components/CommonCompGroupUserList.js
screens/Dashboard.js

group member list component
added component group member list component.
Displays CommonCompGroupUser components horizontally and can be scrolled
Tested on Android and works as expected. Untested on IOS

feat: group member list component finished. (Works on android)

---

components/CommonCompStreak.js
screens/Dashboard.js

Streak component
Added style sheet for streak component.
Visual.

finished CSS design of the streak component

---

pull_request_template.md

added silly emojis for the assignment

---

components/GroupComponentCard.js
package-lock.json
package.json
screens/Dashboard.js

https://trello.com/c/Z2G4bvju/3-group-component
added group component

Group component

---

components/GroupComponentCard.js
screens/Dashboard.js

second group card added and card has new parameters

second card added

---

App.js

https://trello.com/c/xvzLKPqW
This PR sets the initial screen to dashboard
Visual

Set initial page to dashboard

---

navigations/dashboardStack.js
screens/Dashboard.js
screens/GroupInfo.js

view group connected to firebase
firebase and viewGroup connected and unique screens per group

viewGroup connected with Firebase

---

components/CommonCompAlert.js
navigations/dashboardStack.js
screens/CreateGroup.js
screens/Dashboard.js
screens/JoinGroup.js

https://trello.com/c/w4HO6AiZ
This PR adds the verification for group ID based on the firebase database. Currently, it does not add person to the group since we don't have `peopleId` in the database. A ticket will be created in the future to address that.
Visual (alert) by testing valid and invalid groupIds
Valid groupId: 17896, 17901,17902,17903

Join group functionality

---

App.js
components/CommonCompGroupCard.js
screens/CreateGroup.js
screens/Dashboard.js
screens/JoinGroup.js

https://trello.com/c/yEWtaczX
CreateGroup now links current user to the groupMembers.
In Dashboard, it will only display the users who are part of the groupMemberList.
Test against firebase database

CreateGroup should link current user to the groupMembers.

---

screens/Dashboard.js

https://trello.com/c/tBLO0OUb
fixed connection between dashboard/firebase so it loads currently and updates immediately upon new group creation
works on web/iOS

Dashboard firebase connection fixed

---

App.js
components/CommonCompGroupCard.js
components/CommonCompHabitChart.js
screens/Dashboard.js
screens/GroupInfo.js

https://trello.com/c/WIapu67X/61-fe-add-color-functionality
Color selection propagates through 
works on Android

Group color option

---

components/CommonCompGroupUserList.js
screens/Dashboard.js

https://trello.com/c/traHPeuC/73-be-change-userids-to-member-names-on-group-card
Changed groupcards from displaying ids to displaying names
working on android

changed userID to usernames group card

---

components/CommonCompGroupUserList.js
components/CommonCompHabitChart.js
screens/Dashboard.js
screens/GroupInfo.js

https://trello.com/c/xDhU7Sjy/69-be-calculate-streak
Added Streak functionality
Working on android

Streak Functionality

---

navigations/dashboardStack.js
screens/CreateGroup.js
screens/Dashboard.js
screens/GroupInfo.js
utils/color.js

https://trello.com/c/UxwA6Bxg/55-fe-change-the-text-of-complete-today-group-card-add-an-arrow-and-a-shadow-also-changed-the-two-buttons-to-just-one-in-group-info
made things a little prettier? idk
iOS and web

Dan pat/1button

---

screens/CreateGroup.js

remove habit frequency choices and default to daily
remove options to set habit frequency - default to daily
works on ios

remove habit frequency - default to daily

---

screens/CreateGroup.js
screens/Dashboard.js
screens/GroupInfo.js
screens/JoinGroup.js
utils/genRandom.js

added fixes for join group

---

App.js
screens/GroupInfo.js

https://trello.com/c/EDuy8xRb/82-fe-change-the-second-group-info-card-to-not-be-hardcoded-but-really-functional
This is just a placeholder to make the second card on group info page more general for all habits, but if we want, can definitely change to make more functional

like 2 lines of change

---

screens/Chat.js
screens/GroupInfo.js

https://trello.com/c/TkOMoyWP
This PR enables our chat feature to read the first name directly from firebase database as well as user Id. Removed the redundancy of asking user to enter their name.
Testing against the database.

Chat feature partII

---

screens/GroupInfo.js

https://trello.com/c/rbGhXybp
https://trello.com/c/TkOMoyWP
This PR fixes the order of the buttons and reapplied the color so that it looks a little bit better.
Visual

front end changes on the group info page

---

screens/GroupInfo.js

https://trello.com/c/VNzzRF5Q
streak updating correctly and instanteously re-rendering correctly
works on iOS (tested with group of 1,2,3,4,5 people)

fix to streak update sync

---

components/CommonCompGroupUserList.js
screens/Dashboard.js
screens/Login.js

https://trello.com/c/PoUoybzE
This PR fixes the problem when the login is not working for the first time user. It also uses auth to check for changes in state in both login and logout.
Visual and login tests.

Fix login (first time not working)
